const trainSchedules = [
    {
      trainNumber: "LI1-1",
      route: "Lagos - Ibadan",
      timeOfDay: "Morning Train",
      departure: {
        station: "Mobolaji Johnson Station",
        street: "Ebute Metta",
        year: "2025",
        time: "07:03",
        date: "12 - Mar - 2025",
      },
      arrival: {
        station: "Professor Wole Soyinka Station",
        street: "Abeokuta",
        year: "2025",
        time: "08:45",
        date: "12 - Mar - 2025",
      },
      duration: "1 hr, 42 mins",
      classes: [
        {
          type: "First Class",
          priceAdult: "₦6000",
          priceChild: "₦4500",
          reserved: 12,
        },
        {
          type: "Business Class",
          priceAdult: "₦5000",
          priceChild: "₦4000",
          reserved: 9,
        },
        {
          type: "Standard Class",
          priceAdult: "₦3000",
          priceChild: "₦2500",
          reserved: 7,
        },
      ],
    },
    {
      trainNumber: "LI1-2",
      route: "Lagos - Ibadan",
      timeOfDay: "Morning Train",
      departure: {
        station: "Babatunde Raji Fashola Station",
        street: "Agege",
        year: "2025",
        time: "07:03",
        date: "23 - Mar - 2025",
      },
      arrival: {
        station: "Lateef Kayode Jakande Station",
        street: "Agbado",
        year: "2025",
        time: "08:45",
        date: "23 - Mar - 2025",
      },
      duration: "1 hr, 42 mins",
      classes: [
        {
          type: "First Class",
          priceAdult: "₦6000",
          priceChild: "₦4500",
          reserved: 10,
        },
        {
          type: "Business Class",
          priceAdult: "₦5000",
          priceChild: "₦4000",
          reserved: 15,
        },
        {
          type: "Standard Class",
          priceAdult: "₦3000",
          priceChild: "₦2500",
          reserved: 8,
        },
      ],
    },
    {
      trainNumber: "LI1-3",
      route: "Lagos - Ibadan",
      timeOfDay: "Morning Train",
      departure: {
        station: "Professor Yemi Osinbajo Station",
        street: "Kajola",
        year: "2025",
        time: "07:03",
        date: "04 - Apr - 2025",
      },
      arrival: {
        station: "Olu Fumilayo Ransome Kuti Station",
        street: "Papalanto",
        year: "2025",
        time: "08:45",
        date: "04 - Apr - 2025",
      },
      duration: "1 hr, 42 mins",
      classes: [
        {
          type: "First Class",
          priceAdult: "₦6000",
          priceChild: "₦4500",
          reserved: 14,
        },
        {
          type: "Business Class",
          priceAdult: "₦5000",
          priceChild: "₦4000",
          reserved: 20,
        },
        {
          type: "Standard Class",
          priceAdult: "₦3000",
          priceChild: "₦2500",
          reserved: 5,
        },
      ],
    },
    {
      trainNumber: "LI1-4",
      route: "Lagos - Ibadan",
      timeOfDay: "Morning Train",
      departure: {
        station: "Aremo Olusegun Osoba Station",
        street: "Olodo",
        year: "2025",
        time: "07:03",
        date: "18 - May - 2025",
      },
      arrival: {
        station: "Ladoke Akintola Station",
        street: "Omi-Adio",
        year: "2025",
        time: "08:45",
        date: "18 - May - 2025",
      },
      duration: "1 hr, 42 mins",
      classes: [
        {
          type: "First Class",
          priceAdult: "₦6000",
          priceChild: "₦4500",
          reserved: 9,
        },
        {
          type: "Business Class",
          priceAdult: "₦5000",
          priceChild: "₦4000",
          reserved: 11,
        },
        {
          type: "Standard Class",
          priceAdult: "₦3000",
          priceChild: "₦2500",
          reserved: 13,
        },
      ],
    },
    {
      trainNumber: "LI1-5",
      route: "Lagos - Ibadan",
      timeOfDay: "Morning Train",
      departure: {
        station: "Mobolaji Johnson Station",
        street: "Ebute Metta",
        year: "2025",
        time: "07:03",
        date: "02 - Jul - 2025",
      },
      arrival: {
        station: "Obafemi Awolowo Station",
        street: "Moniya",
        year: "2025",
        time: "08:45",
        date: "02 - Jul - 2025",
      },
      duration: "1 hr, 42 mins",
      classes: [
        {
          type: "First Class",
          priceAdult: "₦6000",
          priceChild: "₦4500",
          reserved: 18,
        },
        {
          type: "Business Class",
          priceAdult: "₦5000",
          priceChild: "₦4000",
          reserved: 6,
        },
        {
          type: "Standard Class",
          priceAdult: "₦3000",
          priceChild: "₦2500",
          reserved: 10,
        },
      ],
    },
  
    {
      trainNumber: "IL2-1",
      route: "Ibadan - Lagos",
      timeOfDay: "Morning Train",
      departure: {
        station: "Obafemi Awolowo Station",
        street: "Moniya",
        year: "2025",
        time: "07:03",
        date: "05 - Mar - 2025",
      },
      arrival: {
        station: "Professor Wole Soyinka Station",
        street: "Abeokuta",
        year: "2025",
        time: "08:45",
        date: "05 - Mar - 2025",
      },
      duration: "1 hr, 42 mins",
      classes: [
        {
          type: "First Class",
          priceAdult: "₦6000",
          priceChild: "₦4500",
          reserved: 8,
        },
        {
          type: "Business Class",
          priceAdult: "₦5000",
          priceChild: "₦4000",
          reserved: 14,
        },
        {
          type: "Standard Class",
          priceAdult: "₦3000",
          priceChild: "₦2500",
          reserved: 9,
        },
      ],
    },
    {
      trainNumber: "IL2-2",
      route: "Ibadan - Lagos",
      timeOfDay: "Morning Train",
      departure: {
        station: "Lateef Kayode Jakande Station",
        street: "Agbado",
        year: "2025",
        time: "07:03",
        date: "19 - Mar - 2025",
      },
      arrival: {
        station: "Babatunde Raji Fashola Station",
        street: "Agege",
        year: "2025",
        time: "08:45",
        date: "19 - Mar - 2025",
      },
      duration: "1 hr, 42 mins",
      classes: [
        {
          type: "First Class",
          priceAdult: "₦6000",
          priceChild: "₦4500",
          reserved: 10,
        },
        {
          type: "Business Class",
          priceAdult: "₦5000",
          priceChild: "₦4000",
          reserved: 7,
        },
        {
          type: "Standard Class",
          priceAdult: "₦3000",
          priceChild: "₦2500",
          reserved: 12,
        },
      ],
    },
    {
      trainNumber: "IL2-3",
      route: "Ibadan - Lagos",
      timeOfDay: "Morning Train",
      departure: {
        station: "Olu Fumilayo Ransome Kuti Station",
        street: "Papalanto",
        year: "2025",
        time: "07:03",
        date: "03 - Apr - 2025",
      },
      arrival: {
        station: "Professor Yemi Osinbajo Station",
        street: "Kajola",
        year: "2025",
        time: "08:45",
        date: "03 - Apr - 2025",
      },
      duration: "1 hr, 42 mins",
      classes: [
        {
          type: "First Class",
          priceAdult: "₦6000",
          priceChild: "₦4500",
          reserved: 16,
        },
        {
          type: "Business Class",
          priceAdult: "₦5000",
          priceChild: "₦4000",
          reserved: 20,
        },
        {
          type: "Standard Class",
          priceAdult: "₦3000",
          priceChild: "₦2500",
          reserved: 5,
        },
      ],
    },
    {
      trainNumber: "IL2-4",
      route: "Ibadan - Lagos",
      timeOfDay: "Morning Train",
      departure: {
        station: "Ladoke Akintola Station",
        street: "Omi-Adio",
        year: "2025",
        time: "07:03",
        date: "15 - May - 2025",
      },
      arrival: {
        station: "Aremo Olusegun Osoba Station",
        street: "Olodo",
        year: "2025",
        time: "08:45",
        date: "15 - May - 2025",
      },
      duration: "1 hr, 42 mins",
      classes: [
        {
          type: "First Class",
          priceAdult: "₦6000",
          priceChild: "₦4500",
          reserved: 22,
        },
        {
          type: "Business Class",
          priceAdult: "₦5000",
          priceChild: "₦4000",
          reserved: 13,
        },
        {
          type: "Standard Class",
          priceAdult: "₦3000",
          priceChild: "₦2500",
          reserved: 8,
        },
      ],
    },
    {
      trainNumber: "IL2-5",
      route: "Ibadan - Lagos",
      timeOfDay: "Morning Train",
      departure: {
        station: "Obafemi Awolowo Station",
        street: "Moniya",
        year: "2025",
        time: "07:03",
        date: "28 - Jun - 2025",
      },
      arrival: {
        station: "Mobolaji Johnson Station",
        street: "Ebute Metta",
        year: "2025",
        time: "08:45",
        date: "28 - Jun - 2025",
      },
      duration: "1 hr, 42 mins",
      classes: [
        {
          type: "First Class",
          priceAdult: "₦6000",
          priceChild: "₦4500",
          reserved: 6,
        },
        {
          type: "Business Class",
          priceAdult: "₦5000",
          priceChild: "₦4000",
          reserved: 9,
        },
        {
          type: "Standard Class",
          priceAdult: "₦3000",
          priceChild: "₦2500",
          reserved: 14,
        },
      ],
    },
  
    {
      trainNumber: "LI3-1",
      route: "Lagos - Ibadan",
      timeOfDay: "Morning Train",
      departure: {
        station: "Mobolaji Johnson Station",
        street: "Ebute Metta",
        year: "2025",
        time: "10:03",
        date: "08 - Mar - 2025",
      },
      arrival: {
        station: "Professor Wole Soyinka Station",
        street: "Abeokuta",
        year: "2025",
        time: "11:45",
        date: "08 - Mar - 2025",
      },
      duration: "1 hr, 42 mins",
      classes: [
        {
          type: "First Class",
          priceAdult: "₦6000",
          priceChild: "₦4500",
          reserved: 12,
        },
        {
          type: "Business Class",
          priceAdult: "₦5000",
          priceChild: "₦4000",
          reserved: 20,
        },
        {
          type: "Standard Class",
          priceAdult: "₦3000",
          priceChild: "₦2500",
          reserved: 5,
        },
      ],
    },
    {
      trainNumber: "LI3-2",
      route: "Lagos - Ibadan",
      timeOfDay: "Morning Train",
      departure: {
        station: "Babatunde Raji Fashola Station",
        street: "Agege",
        year: "2025",
        time: "10:03",
        date: "20 - Mar - 2025",
      },
      arrival: {
        station: "Lateef Kayode Jakande Station",
        street: "Agbado",
        year: "2025",
        time: "11:45",
        date: "20 - Mar - 2025",
      },
      duration: "1 hr, 42 mins",
      classes: [
        {
          type: "First Class",
          priceAdult: "₦6000",
          priceChild: "₦4500",
          reserved: 25,
        },
        {
          type: "Business Class",
          priceAdult: "₦5000",
          priceChild: "₦4000",
          reserved: 10,
        },
        {
          type: "Standard Class",
          priceAdult: "₦3000",
          priceChild: "₦2500",
          reserved: 6,
        },
      ],
    },
    {
      trainNumber: "LI3-3",
      route: "Lagos - Ibadan",
      timeOfDay: "Morning Train",
      departure: {
        station: "Professor Yemi Osinbajo Station",
        street: "Kajola",
        year: "2025",
        time: "10:03",
        date: "07 - Apr - 2025",
      },
      arrival: {
        station: "Olu Fumilayo Ransome Kuti Station",
        street: "Papalanto",
        year: "2025",
        time: "11:45",
        date: "07 - Apr - 2025",
      },
      duration: "1 hr, 42 mins",
      classes: [
        {
          type: "First Class",
          priceAdult: "₦6000",
          priceChild: "₦4500",
          reserved: 11,
        },
        {
          type: "Business Class",
          priceAdult: "₦5000",
          priceChild: "₦4000",
          reserved: 17,
        },
        {
          type: "Standard Class",
          priceAdult: "₦3000",
          priceChild: "₦2500",
          reserved: 9,
        },
      ],
    },
    {
      trainNumber: "LI3-4",
      route: "Lagos - Ibadan",
      timeOfDay: "Morning Train",
      departure: {
        station: "Aremo Olusegun Osoba Station",
        street: "Olodo",
        year: "2025",
        time: "10:03",
        date: "01 - May - 2025",
      },
      arrival: {
        station: "Ladoke Akintola Station",
        street: "Omi-Adio",
        year: "2025",
        time: "11:45",
        date: "01 - May - 2025",
      },
      duration: "1 hr, 42 mins",
      classes: [
        {
          type: "First Class",
          priceAdult: "₦6000",
          priceChild: "₦4500",
          reserved: 8,
        },
        {
          type: "Business Class",
          priceAdult: "₦5000",
          priceChild: "₦4000",
          reserved: 14,
        },
        {
          type: "Standard Class",
          priceAdult: "₦3000",
          priceChild: "₦2500",
          reserved: 10,
        },
      ],
    },
    {
      trainNumber: "LI3-5",
      route: "Lagos - Ibadan",
      timeOfDay: "Morning Train",
      departure: {
        station: "Mobolaji Johnson Station",
        street: "Ebute Metta",
        year: "2025",
        time: "10:03",
        date: "17 - Jul - 2025",
      },
      arrival: {
        station: "Obafemi Awolowo Station",
        street: "Moniya",
        year: "2025",
        time: "11:45",
        date: "17 - Jul - 2025",
      },
      duration: "1 hr, 42 mins",
      classes: [
        {
          type: "First Class",
          priceAdult: "₦6000",
          priceChild: "₦4500",
          reserved: 13,
        },
        {
          type: "Business Class",
          priceAdult: "₦5000",
          priceChild: "₦4000",
          reserved: 19,
        },
        {
          type: "Standard Class",
          priceAdult: "₦3000",
          priceChild: "₦2500",
          reserved: 8,
        },
      ],
    },
  
    {
      trainNumber: "IL4-1",
      route: "Ibadan - Lagos",
      timeOfDay: "Afternoon Train",
      departure: {
        station: "Obafemi Awolowo Station",
        street: "Moniya",
        year: "2025",
        time: "11:03",
        date: "10 - Mar - 2025",
      },
      arrival: {
        station: "Professor Wole Soyinka Station",
        street: "Abeokuta",
        year: "2025",
        time: "12:45",
        date: "10 - Mar - 2025",
      },
      duration: "1 hr, 42 mins",
      classes: [
        {
          type: "First Class",
          priceAdult: "₦6000",
          priceChild: "₦4500",
          reserved: 6,
        },
        {
          type: "Business Class",
          priceAdult: "₦5000",
          priceChild: "₦4000",
          reserved: 12,
        },
        {
          type: "Standard Class",
          priceAdult: "₦3000",
          priceChild: "₦2500",
          reserved: 9,
        },
      ],
    },
    {
      trainNumber: "IL4-2",
      route: "Ibadan - Lagos",
      timeOfDay: "Afternoon Train",
      departure: {
        station: "Lateef Kayode Jakande Station",
        street: "Agbado",
        year: "2025",
        time: "11:03",
        date: "22 - Apr - 2025",
      },
      arrival: {
        station: "Babatunde Raji Fashola Station",
        street: "Agege",
        year: "2025",
        time: "12:45",
        date: "22 - Apr - 2025",
      },
      duration: "1 hr, 42 mins",
      classes: [
        {
          type: "First Class",
          priceAdult: "₦6000",
          priceChild: "₦4500",
          reserved: 18,
        },
        {
          type: "Business Class",
          priceAdult: "₦5000",
          priceChild: "₦4000",
          reserved: 8,
        },
        {
          type: "Standard Class",
          priceAdult: "₦3000",
          priceChild: "₦2500",
          reserved: 14,
        },
      ],
    },
    {
      trainNumber: "IL4-3",
      route: "Ibadan - Lagos",
      timeOfDay: "Afternoon Train",
      departure: {
        station: "Olu Fumilayo Ransome Kuti Station",
        street: "Papalanto",
        year: "2025",
        time: "11:03",
        date: "08 - May - 2025",
      },
      arrival: {
        station: "Professor Yemi Osinbajo Station",
        street: "Kajola",
        year: "2025",
        time: "12:45",
        date: "08 - May - 2025",
      },
      duration: "1 hr, 42 mins",
      classes: [
        {
          type: "First Class",
          priceAdult: "₦6000",
          priceChild: "₦4500",
          reserved: 9,
        },
        {
          type: "Business Class",
          priceAdult: "₦5000",
          priceChild: "₦4000",
          reserved: 21,
        },
        {
          type: "Standard Class",
          priceAdult: "₦3000",
          priceChild: "₦2500",
          reserved: 7,
        },
      ],
    },
    {
      trainNumber: "IL4-4",
      route: "Ibadan - Lagos",
      timeOfDay: "Afternoon Train",
      departure: {
        station: "Ladoke Akintola Station",
        street: "Omi-Adio",
        year: "2025",
        time: "11:03",
        date: "16 - Jun - 2025",
      },
      arrival: {
        station: "Aremo Olusegun Osoba Station",
        street: "Olodo",
        year: "2025",
        time: "12:45",
        date: "16 - Jun - 2025",
      },
      duration: "1 hr, 42 mins",
      classes: [
        {
          type: "First Class",
          priceAdult: "₦6000",
          priceChild: "₦4500",
          reserved: 11,
        },
        {
          type: "Business Class",
          priceAdult: "₦5000",
          priceChild: "₦4000",
          reserved: 6,
        },
        {
          type: "Standard Class",
          priceAdult: "₦3000",
          priceChild: "₦2500",
          reserved: 10,
        },
      ],
    },
    {
      trainNumber: "IL4-5",
      route: "Ibadan - Lagos",
      timeOfDay: "Afternoon Train",
      departure: {
        station: "Obafemi Awolowo Station",
        street: "Moniya",
        year: "2025",
        time: "11:03",
        date: "27 - Jul - 2025",
      },
      arrival: {
        station: "Mobolaji Johnson Station",
        street: "Ebute Metta",
        year: "2025",
        time: "12:45",
        date: "27 - Jul - 2025",
      },
      duration: "1 hr, 42 mins",
      classes: [
        {
          type: "First Class",
          priceAdult: "₦6000",
          priceChild: "₦4500",
          reserved: 13,
        },
        {
          type: "Business Class",
          priceAdult: "₦5000",
          priceChild: "₦4000",
          reserved: 10,
        },
        {
          type: "Standard Class",
          priceAdult: "₦3000",
          priceChild: "₦2500",
          reserved: 5,
        },
      ],
    },
  
    {
      trainNumber: "LI5-1",
      route: "Lagos - Ibadan",
      timeOfDay: "Afternoon Train",
      departure: {
        station: "Mobolaji Johnson Station",
        street: "Ebute Metta",
        year: "2025",
        time: "13:03",
        date: "02 - Mar - 2025",
      },
      arrival: {
        station: "Professor Wole Soyinka Station",
        street: "Abeokuta",
        year: "2025",
        time: "14:45",
        date: "02 - Mar - 2025",
      },
      duration: "1 hr, 42 mins",
      classes: [
        {
          type: "First Class",
          priceAdult: "₦6000",
          priceChild: "₦4500",
          reserved: 7,
        },
        {
          type: "Business Class",
          priceAdult: "₦5000",
          priceChild: "₦4000",
          reserved: 12,
        },
        {
          type: "Standard Class",
          priceAdult: "₦3000",
          priceChild: "₦2500",
          reserved: 15,
        },
      ],
    },
    {
      trainNumber: "LI5-2",
      route: "Lagos - Ibadan",
      timeOfDay: "Afternoon Train",
      departure: {
        station: "Babatunde Raji Fashola Station",
        street: "Agege",
        year: "2025",
        time: "13:03",
        date: "11 - Apr - 2025",
      },
      arrival: {
        station: "Lateef Kayode Jakande Station",
        street: "Agbado",
        year: "2025",
        time: "14:45",
        date: "11 - Apr - 2025",
      },
      duration: "1 hr, 42 mins",
      classes: [
        {
          type: "First Class",
          priceAdult: "₦6000",
          priceChild: "₦4500",
          reserved: 5,
        },
        {
          type: "Business Class",
          priceAdult: "₦5000",
          priceChild: "₦4000",
          reserved: 16,
        },
        {
          type: "Standard Class",
          priceAdult: "₦3000",
          priceChild: "₦2500",
          reserved: 9,
        },
      ],
    },
    {
      trainNumber: "LI5-3",
      route: "Lagos - Ibadan",
      timeOfDay: "Afternoon Train",
      departure: {
        station: "Professor Yemi Osinbajo Station",
        street: "Kajola",
        year: "2025",
        time: "13:03",
        date: "24 - May - 2025",
      },
      arrival: {
        station: "Olu Fumilayo Ransome Kuti Station",
        street: "Papalanto",
        year: "2025",
        time: "14:45",
        date: "24 - May - 2025",
      },
      duration: "1 hr, 42 mins",
      classes: [
        {
          type: "First Class",
          priceAdult: "₦6000",
          priceChild: "₦4500",
          reserved: 8,
        },
        {
          type: "Business Class",
          priceAdult: "₦5000",
          priceChild: "₦4000",
          reserved: 14,
        },
        {
          type: "Standard Class",
          priceAdult: "₦3000",
          priceChild: "₦2500",
          reserved: 11,
        },
      ],
    },
    {
      trainNumber: "LI5-4",
      route: "Lagos - Ibadan",
      timeOfDay: "Afternoon Train",
      departure: {
        station: "Aremo Olusegun Osoba Station",
        street: "Olodo",
        year: "2025",
        time: "13:03",
        date: "06 - Jun - 2025",
      },
      arrival: {
        station: "Ladoke Akintola Station",
        street: "Omi-Adio",
        year: "2025",
        time: "14:45",
        date: "06 - Jun - 2025",
      },
      duration: "1 hr, 42 mins",
      classes: [
        {
          type: "First Class",
          priceAdult: "₦6000",
          priceChild: "₦4500",
          reserved: 17,
        },
        {
          type: "Business Class",
          priceAdult: "₦5000",
          priceChild: "₦4000",
          reserved: 8,
        },
        {
          type: "Standard Class",
          priceAdult: "₦3000",
          priceChild: "₦2500",
          reserved: 10,
        },
      ],
    },
    {
      trainNumber: "LI5-5",
      route: "Lagos - Ibadan",
      timeOfDay: "Afternoon Train",
      departure: {
        station: "Mobolaji Johnson Station",
        street: "Ebute Metta",
        year: "2025",
        time: "13:03",
        date: "29 - Jul - 2025",
      },
      arrival: {
        station: "Obafemi Awolowo Station",
        street: "Moniya",
        year: "2025",
        time: "14:45",
        date: "29 - Jul - 2025",
      },
      duration: "1 hr, 42 mins",
      classes: [
        {
          type: "First Class",
          priceAdult: "₦6000",
          priceChild: "₦4500",
          reserved: 20,
        },
        {
          type: "Business Class",
          priceAdult: "₦5000",
          priceChild: "₦4000",
          reserved: 10,
        },
        {
          type: "Standard Class",
          priceAdult: "₦3000",
          priceChild: "₦2500",
          reserved: 8,
        },
      ],
    },
  
    {
      trainNumber: "IL4E-1",
      route: "Ibadan - Lagos",
      timeOfDay: "Evening Train",
      departure: {
        station: "Obafemi Awolowo Station",
        street: "Moniya",
        year: "2025",
        time: "16:03",
        date: "04 - Mar - 2025",
      },
      arrival: {
        station: "Professor Wole Soyinka Station",
        street: "Abeokuta",
        year: "2025",
        time: "17:45",
        date: "04 - Mar - 2025",
      },
      duration: "1 hr, 42 mins",
      classes: [
        {
          type: "First Class",
          priceAdult: "₦6000",
          priceChild: "₦4500",
          reserved: 5,
        },
        {
          type: "Business Class",
          priceAdult: "₦5000",
          priceChild: "₦4000",
          reserved: 12,
        },
        {
          type: "Standard Class",
          priceAdult: "₦3000",
          priceChild: "₦2500",
          reserved: 9,
        },
      ],
    },
    {
      trainNumber: "IL4E-2",
      route: "Ibadan - Lagos",
      timeOfDay: "Evening Train",
      departure: {
        station: "Lateef Kayode Jakande Station",
        street: "Agbado",
        year: "2025",
        time: "16:03",
        date: "21 - Apr - 2025",
      },
      arrival: {
        station: "Babatunde Raji Fashola Station",
        street: "Agege",
        year: "2025",
        time: "17:45",
        date: "21 - Apr - 2025",
      },
      duration: "1 hr, 42 mins",
      classes: [
        {
          type: "First Class",
          priceAdult: "₦6000",
          priceChild: "₦4500",
          reserved: 18,
        },
        {
          type: "Business Class",
          priceAdult: "₦5000",
          priceChild: "₦4000",
          reserved: 7,
        },
        {
          type: "Standard Class",
          priceAdult: "₦3000",
          priceChild: "₦2500",
          reserved: 11,
        },
      ],
    },
    {
      trainNumber: "IL4E-3",
      route: "Ibadan - Lagos",
      timeOfDay: "Evening Train",
      departure: {
        station: "Olu Fumilayo Ransome Kuti Station",
        street: "Papalanto",
        year: "2025",
        time: "16:03",
        date: "09 - May - 2025",
      },
      arrival: {
        station: "Professor Yemi Osinbajo Station",
        street: "Kajola",
        year: "2025",
        time: "17:45",
        date: "09 - May - 2025",
      },
      duration: "1 hr, 42 mins",
      classes: [
        {
          type: "First Class",
          priceAdult: "₦6000",
          priceChild: "₦4500",
          reserved: 14,
        },
        {
          type: "Business Class",
          priceAdult: "₦5000",
          priceChild: "₦4000",
          reserved: 5,
        },
        {
          type: "Standard Class",
          priceAdult: "₦3000",
          priceChild: "₦2500",
          reserved: 17,
        },
      ],
    },
    {
      trainNumber: "IL4E-4",
      route: "Ibadan - Lagos",
      timeOfDay: "Evening Train",
      departure: {
        station: "Ladoke Akintola Station",
        street: "Omi-Adio",
        year: "2025",
        time: "16:03",
        date: "18 - Jun - 2025",
      },
      arrival: {
        station: "Aremo Olusegun Osoba Station",
        street: "Olodo",
        year: "2025",
        time: "17:45",
        date: "18 - Jun - 2025",
      },
      duration: "1 hr, 42 mins",
      classes: [
        {
          type: "First Class",
          priceAdult: "₦6000",
          priceChild: "₦4500",
          reserved: 20,
        },
        {
          type: "Business Class",
          priceAdult: "₦5000",
          priceChild: "₦4000",
          reserved: 9,
        },
        {
          type: "Standard Class",
          priceAdult: "₦3000",
          priceChild: "₦2500",
          reserved: 10,
        },
      ],
    },
    {
      trainNumber: "IL4E-5",
      route: "Ibadan - Lagos",
      timeOfDay: "Evening Train",
      departure: {
        station: "Obafemi Awolowo Station",
        street: "Moniya",
        year: "2025",
        time: "16:03",
        date: "05 - Jul - 2025",
      },
      arrival: {
        station: "Mobolaji Johnson Station",
        street: "Ebute Metta",
        year: "2025",
        time: "17:45",
        date: "05 - Jul - 2025",
      },
      duration: "1 hr, 42 mins",
      classes: [
        {
          type: "First Class",
          priceAdult: "₦6000",
          priceChild: "₦4500",
          reserved: 15,
        },
        {
          type: "Business Class",
          priceAdult: "₦5000",
          priceChild: "₦4000",
          reserved: 11,
        },
        {
          type: "Standard Class",
          priceAdult: "₦3000",
          priceChild: "₦2500",
          reserved: 8,
        },
      ],
    },
  
    {
      trainNumber: "LI3E-1",
      route: "Lagos - Ibadan",
      timeOfDay: "Evening Train",
      departure: {
        station: "Mobolaji Johnson Station",
        street: "Ebute Metta",
        year: "2025",
        time: "15:30",
        date: "06 - Mar - 2025",
      },
      arrival: {
        station: "Professor Wole Soyinka Station",
        street: "Abeokuta",
        year: "2025",
        time: "17:15",
        date: "06 - Mar - 2025",
      },
      duration: "1 hr, 45 mins",
      classes: [
        {
          type: "First Class",
          priceAdult: "₦6000",
          priceChild: "₦4500",
          reserved: 5,
        },
        {
          type: "Business Class",
          priceAdult: "₦5000",
          priceChild: "₦4000",
          reserved: 18,
        },
        {
          type: "Standard Class",
          priceAdult: "₦3000",
          priceChild: "₦2500",
          reserved: 9,
        },
      ],
    },
    {
      trainNumber: "LI3E-2",
      route: "Lagos - Ibadan",
      timeOfDay: "Evening Train",
      departure: {
        station: "Babatunde Raji Fashola Station",
        street: "Agege",
        year: "2025",
        time: "15:30",
        date: "27 - Apr - 2025",
      },
      arrival: {
        station: "Lateef Kayode Jakande Station",
        street: "Agbado",
        year: "2025",
        time: "17:15",
        date: "27 - Apr - 2025",
      },
      duration: "1 hr, 45 mins",
      classes: [
        {
          type: "First Class",
          priceAdult: "₦6000",
          priceChild: "₦4500",
          reserved: 13,
        },
        {
          type: "Business Class",
          priceAdult: "₦5000",
          priceChild: "₦4000",
          reserved: 7,
        },
        {
          type: "Standard Class",
          priceAdult: "₦3000",
          priceChild: "₦2500",
          reserved: 16,
        },
      ],
    },
    {
      trainNumber: "LI3E-3",
      route: "Lagos - Ibadan",
      timeOfDay: "Evening Train",
      departure: {
        station: "Professor Yemi Osinbajo Station",
        street: "Kajola",
        year: "2025",
        time: "15:30",
        date: "10 - May - 2025",
      },
      arrival: {
        station: "Olu Fumilayo Ransome Kuti Station",
        street: "Papalanto",
        year: "2025",
        time: "17:15",
        date: "10 - May - 2025",
      },
      duration: "1 hr, 45 mins",
      classes: [
        {
          type: "First Class",
          priceAdult: "₦6000",
          priceChild: "₦4500",
          reserved: 21,
        },
        {
          type: "Business Class",
          priceAdult: "₦5000",
          priceChild: "₦4000",
          reserved: 9,
        },
        {
          type: "Standard Class",
          priceAdult: "₦3000",
          priceChild: "₦2500",
          reserved: 8,
        },
      ],
    },
    {
      trainNumber: "LI3E-4",
      route: "Lagos - Ibadan",
      timeOfDay: "Evening Train",
      departure: {
        station: "Aremo Olusegun Osoba Station",
        street: "Olodo",
        year: "2025",
        time: "15:30",
        date: "14 - Jun - 2025",
      },
      arrival: {
        station: "Ladoke Akintola Station",
        street: "Omi-Adio",
        year: "2025",
        time: "17:15",
        date: "14 - Jun - 2025",
      },
      duration: "1 hr, 45 mins",
      classes: [
        {
          type: "First Class",
          priceAdult: "₦6000",
          priceChild: "₦4500",
          reserved: 17,
        },
        {
          type: "Business Class",
          priceAdult: "₦5000",
          priceChild: "₦4000",
          reserved: 11,
        },
        {
          type: "Standard Class",
          priceAdult: "₦3000",
          priceChild: "₦2500",
          reserved: 9,
        },
      ],
    },
    {
      trainNumber: "LI3E-5",
      route: "Lagos - Ibadan",
      timeOfDay: "Evening Train",
      departure: {
        station: "Mobolaji Johnson Station",
        street: "Ebute Metta",
        year: "2025",
        time: "15:30",
        date: "25 - Jul - 2025",
      },
      arrival: {
        station: "Obafemi Awolowo Station",
        street: "Moniya",
        year: "2025",
        time: "17:15",
        date: "25 - Jul - 2025",
      },
      duration: "1 hr, 45 mins",
      classes: [
        {
          type: "First Class",
          priceAdult: "₦6000",
          priceChild: "₦4500",
          reserved: 10,
        },
        {
          type: "Business Class",
          priceAdult: "₦5000",
          priceChild: "₦4000",
          reserved: 6,
        },
        {
          type: "Standard Class",
          priceAdult: "₦3000",
          priceChild: "₦2500",
          reserved: 14,
        },
      ],
    },
  
    {
      trainNumber: "IL6-1",
      route: "Ibadan - Lagos",
      timeOfDay: "Evening Train",
      departure: {
        station: "Obafemi Awolowo Station",
        street: "Moniya",
        year: "2025",
        time: "16:30",
        date: "03 - Mar - 2025",
      },
      arrival: {
        station: "Professor Wole Soyinka Station",
        street: "Abeokuta",
        year: "2025",
        time: "18:15",
        date: "03 - Mar - 2025",
      },
      duration: "1 hr, 45 mins",
      classes: [
        {
          type: "First Class",
          priceAdult: "₦6000",
          priceChild: "₦4500",
          reserved: 15,
        },
        {
          type: "Business Class",
          priceAdult: "₦5000",
          priceChild: "₦4000",
          reserved: 9,
        },
        {
          type: "Standard Class",
          priceAdult: "₦3000",
          priceChild: "₦2500",
          reserved: 5,
        },
      ],
    },
    {
      trainNumber: "IL6-2",
      route: "Ibadan - Lagos",
      timeOfDay: "Evening Train",
      departure: {
        station: "Lateef Kayode Jakande Station",
        street: "Agbado",
        year: "2025",
        time: "16:30",
        date: "14 - Apr - 2025",
      },
      arrival: {
        station: "Babatunde Raji Fashola Station",
        street: "Agege",
        year: "2025",
        time: "18:15",
        date: "14 - Apr - 2025",
      },
      duration: "1 hr, 45 mins",
      classes: [
        {
          type: "First Class",
          priceAdult: "₦6000",
          priceChild: "₦4500",
          reserved: 21,
        },
        {
          type: "Business Class",
          priceAdult: "₦5000",
          priceChild: "₦4000",
          reserved: 10,
        },
        {
          type: "Standard Class",
          priceAdult: "₦3000",
          priceChild: "₦2500",
          reserved: 8,
        },
      ],
    },
    {
      trainNumber: "IL6-3",
      route: "Ibadan - Lagos",
      timeOfDay: "Evening Train",
      departure: {
        station: "Olu Fumilayo Ransome Kuti Station",
        street: "Papalanto",
        year: "2025",
        time: "16:30",
        date: "26 - May - 2025",
      },
      arrival: {
        station: "Professor Yemi Osinbajo Station",
        street: "Kajola",
        year: "2025",
        time: "18:15",
        date: "26 - May - 2025",
      },
      duration: "1 hr, 45 mins",
      classes: [
        {
          type: "First Class",
          priceAdult: "₦6000",
          priceChild: "₦4500",
          reserved: 5,
        },
        {
          type: "Business Class",
          priceAdult: "₦5000",
          priceChild: "₦4000",
          reserved: 18,
        },
        {
          type: "Standard Class",
          priceAdult: "₦3000",
          priceChild: "₦2500",
          reserved: 12,
        },
      ],
    },
    {
      trainNumber: "IL6-4",
      route: "Ibadan - Lagos",
      timeOfDay: "Evening Train",
      departure: {
        station: "Ladoke Akintola Station",
        street: "Omi-Adio",
        year: "2025",
        time: "16:30",
        date: "09 - Jun - 2025",
      },
      arrival: {
        station: "Aremo Olusegun Osoba Station",
        street: "Olodo",
        year: "2025",
        time: "18:15",
        date: "09 - Jun - 2025",
      },
      duration: "1 hr, 45 mins",
      classes: [
        {
          type: "First Class",
          priceAdult: "₦6000",
          priceChild: "₦4500",
          reserved: 14,
        },
        {
          type: "Business Class",
          priceAdult: "₦5000",
          priceChild: "₦4000",
          reserved: 6,
        },
        {
          type: "Standard Class",
          priceAdult: "₦3000",
          priceChild: "₦2500",
          reserved: 10,
        },
      ],
    },
    {
      trainNumber: "IL6-5",
      route: "Ibadan - Lagos",
      timeOfDay: "Evening Train",
      departure: {
        station: "Obafemi Awolowo Station",
        street: "Moniya",
        year: "2025",
        time: "16:30",
        date: "21 - Jul - 2025",
      },
      arrival: {
        station: "Mobolaji Johnson Station",
        street: "Ebute Metta",
        year: "2025",
        time: "18:15",
        date: "21 - Jul - 2025",
      },
      duration: "1 hr, 45 mins",
      classes: [
        {
          type: "First Class",
          priceAdult: "₦6000",
          priceChild: "₦4500",
          reserved: 19,
        },
        {
          type: "Business Class",
          priceAdult: "₦5000",
          priceChild: "₦4000",
          reserved: 8,
        },
        {
          type: "Standard Class",
          priceAdult: "₦3000",
          priceChild: "₦2500",
          reserved: 6,
        },
      ],
    },
  ];
  
  module.exports = trainSchedules;